- .github/workflows/pre-commit.yml
Supports #10
sets up pre-commit as github action
> add pre-commit workflow action

- .github/workflows/yarn.yml
Supports #10 
attempts to run yarn test via github actions instead of TravisCI
> 🤖 Run yarn test with github action

- .github/workflows/eslint.yml
- .github/workflows/tsc.yml
- packages/blocks/src/blocks.ts
Supports #10
Runs eslint and type checking as actions on the PR, and leaves comments inline with errors.
We'll may want to remove eslint from the yarn test if we follow this approach, will speed up builds.
> 👨‍🎤eslint and typecheck github actions with PR annotations

- package.json
- packages/jest-mock-web-client/README.md
- packages/jest-mock-web-client/__mocks__/@slack/web-api.ts
- packages/jest-mock-web-client/jest.config.js
- packages/jest-mock-web-client/package.json
- packages/jest-mock-web-client/src/index.spec.ts
- packages/jest-mock-web-client/src/index.ts
- packages/jest-mock-web-client/tsconfig.json
- yarn.lock
Depends #2 
Publishes a mock slack web-api for jest.
Copied our internal one, wrote tests, documented it, profit.
> Jest mock web client

- .github/workflows/test.yml
fixes double reporting, also faster run time
> 🔧Don't run lint as part of test workflow

- packages/eslint-config/index.js
- packages/fixtures/README.md
- packages/fixtures/src/__snapshots__/fields.spec.ts.snap
- packages/fixtures/src/events.spec.ts
- packages/fixtures/src/events.ts
- packages/fixtures/src/fields.spec.ts
- packages/fixtures/src/fields.ts
- packages/fixtures/src/index.ts
- yarn.lock
Supports #8 
Adds globally overridable fields. These are also just referenceable now which is nice for writing `expect` statements. 
I also threw in a `message` fixture as I needed something without a `response_url` for #8 
* Slightly better docs. 
* New `fields` export
* `message` event
> 🌎 Add global fields and a messages fixture

- packages/jest-mock-web-client/package.json
- packages/jest-mock-web-client/src/index.ts
- yarn.lock
Resolves #28 
Updates the slack web-api version, and the MockWebClient based on the changes to the API.
> 🧹Web api bump

- packages/fixtures/package.json
- packages/jest-bolt-receiver/package.json
- packages/jest-mock-web-client/package.json
- packages/slackctl/package.json
- packages/standards/jest.config.js
- tsconfig.json
Supports #9 
Updates a few missed `main` fields to point to compiled js
Swappy pasta!
> 🚀 Update package.json main fields to point to compiled js

- packages/fixtures/src/events.spec.ts
- packages/fixtures/src/events.ts
Depends #38 
Adds an `appMention` event to the fixtures
Just'a fixture
> 🛋 App mention event fixture

- package.json
- packages/blocks/README.md
- yarn.lock
closes #35 
Just adds a readme with an example. probably should have already been there.
> 📚 add readme for blocks package

- package.json
- packages/blocks/src/__snapshots__/blocks.spec.ts.snap
- packages/blocks/src/__snapshots__/elements.spec.ts.snap
- packages/blocks/src/__snapshots__/index.spec.ts.snap
- packages/blocks/src/blocks.spec.ts
- packages/blocks/src/blocks.ts
- packages/blocks/src/elements.spec.ts
- packages/blocks/src/elements.ts
- packages/blocks/src/formatting.ts
- packages/blocks/src/index.spec.ts
- packages/blocks/src/index.ts
- tsconfig.build.json
- yarn.lock
n/a
`blocks.ts` was a bit messy. Tried to clean up and break out `elements` from `blocks`, as well as group/organize according to the slack docs and add some documentation. Some of this felt like continuous improvement, didn't actually change the interface of anything here other than...
Added a new helper `FieldsSection` to allow passing an array of markdown strings which will then be converted to fields. Feels like a very common pattern, though I imagine further functionality is likely warranted in future updates.
Will leave some comments throughout, but mostly the above.
> 🧹 reorganize elements, add field section helper

- packages/bolt-interactions/README.md
- packages/bolt-interactions/package.json
- packages/bolt-interactions/src/interaction-flow.spec.ts
- packages/bolt-interactions/src/interaction-flow.ts
Allows you to pass in an instance id for a flow and gives some helpers to help parse the guys.
Optional param on `start`, reordered functions to reduce some code distance.
> 👻 Action id parsing bananza

- packages/blocks/package.json
- packages/fixtures/package.json
- packages/fixtures/src/__snapshots__/fields.spec.ts.snap
- packages/fixtures/src/action.spec.ts
- packages/fixtures/src/actions.ts
- packages/fixtures/src/fields.ts
Adds a blockOverflowAction fixture. Releases a new version of fixtures and blocks
Just code 🤷‍♂ 
> 🚀 Add blockOverflowAction fixture

- packages/blocks/src/__snapshots__/blocks.spec.ts.snap
- packages/blocks/src/__snapshots__/elements.spec.ts.snap
- packages/blocks/src/__snapshots__/index.spec.ts.snap
- packages/blocks/src/blocks.spec.ts
- packages/blocks/src/blocks.ts
- packages/blocks/src/elements.spec.ts
- packages/blocks/src/elements.ts
Adds `Input` Block, `StaticSelectInputElement`, and `PlainTextInputElement`.
> 🕹 Add input blocks

- packages/blocks/src/__snapshots__/elements.spec.ts.snap
- packages/blocks/src/elements.spec.ts
small cleanup to tests, mentioned here https://github.com/IBM/slack-wrench/pull/63#discussion_r419823639
> 🧹 channel -> conversation for conversation tests

- packages/jest-mock-web-client/package.json
No issue
This lets TypeScript property resolve the types, and enhances IDE support.
Adds the `types` property to the `package.json`.
> 🧹 Add types property to jest-mock-web-client package.json

- packages/blocks-to-image/package.json
- packages/blocks/package.json
- packages/bolt-interactions/package.json
- packages/bolt-storage-file/package.json
- packages/fixtures/package.json
- packages/jest-bolt-receiver/package.json
- packages/jest-mock-web-client/package.json
- packages/koa-bolt/package.json
- yarn.lock
Release of and fixing the rest of #61 
Adds typings to all the things for systems that still need that.
Copy pasta + a bunch of version updates across all the things.
> Update typings for all libraries and release

- packages/fixtures/package.json
#71
Bumps version as follow up to #71
> ⬆️  bump patch version for fixtures

- .gitignore
- packages/fixtures/package.json
- packages/fixtures/src/action.spec.ts
- packages/fixtures/src/actions.ts
adds blockStaticSelectAction to actions fixture
> 👊 add blockStaticSelectAction to actions fixture

- .eslintignore
- .pre-commit-config.yaml
- package.json
- packages/blocks-to-image/package.json
- packages/blocks/package.json
- packages/blocks/src/blocks.spec.ts
- packages/blocks/src/blocks.ts
- packages/blocks/src/limitHelpers.ts
- packages/bolt-interactions/package.json
- packages/bolt-interactions/src/interaction-flow.spec.ts
- packages/bolt-interactions/src/interaction-flow.ts
- packages/bolt-storage-file/package.json
- packages/bolt-storage-file/src/index.ts
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- packages/fixtures/src/serverless-tester.spec.ts
- packages/jest-mock-web-client/package.json
- packages/jest-mock-web-client/src/index.spec.ts
- packages/jest-mock-web-client/src/index.ts
- packages/koa-bolt/package.json
- packages/koa-bolt/src/index.spec.ts
- packages/koa-bolt/src/index.ts
- packages/standards/jest.config.js
- yarn.lock
Upgrade all the project dependencies and fix the fallout from major updates.
Will leave comments, basically just a lot of additional typing b/c eslint-typescript has gotten better.
> 🧹 Upgrade project dependencies

- .github/workflows/main.yml
- .pre-commit-config.yaml
- packages/bolt-interactions/src/types/interaction.ts
PRs are currently failing as the old pre-commit job used deprecated functionality. This PR updates all things pre-commit
I removed the pre-commit cache, but the v2 version has it built in 🚀 
> chore: update pre-commit action and version

- packages/koa-bolt/package.json
- yarn.lock
> chore: update koa-bolt to 1.3.0

- packages/blocks/package.json
Supports #105 
Releases blocks 3.1.2
> chore: 🚀 release blocks 3.1.2

- .github/workflows/main.yml
- README.md
- packages/bolt-storage-file/src/index.spec.ts
- packages/fixtures/README.md
- packages/fixtures/src/events.ts
- packages/fixtures/src/view.ts
- packages/jest-mock-web-client/src/index.ts
- packages/koa-bolt/README.md
Words matter. Updating master to `main` -> https://github.com/github/renaming
> chore: update default branch to main

- packages/jest-mock-web-client/package.json
- packages/jest-mock-web-client/src/index.ts
Fixes #70 
Publishes #123 
Releases new version of jest mock web client and adds support for jest deprecations
> chore: publish jest-mock-web-client@1.4.0
